### ISSUE TITLE
ClyMetalinkCommand should be marked as abstract

### ISSUE THREAD

**Issue by oliveiraallex** [pharo-ide/SystemCommands#70]
The modification of isAbstract in SycSourceCodeCommand is failing to detect the classes that are abstract. If there is no logic in the superclass to detect if the class is abstract we should modify the sub class to respond abstract = true

**Comment by dionisiydk** [comment]
It should be already resolved. I did wrong minor version update. Then I
removed it.
Try to rebuild pharothings

вт, 26 мар. 2019 г., 9:42 oliveiraallex <notifications@github.com>:

**Comment by oliveiraallex** [comment]
Yes, I rebuild it and now it is working. Thanks Denis!
